name: Deploy

on:
  push:
    branches: [ master, develop ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Deploy
      shell: bash
      env:
        CICD: "*"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
        COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}
        COGNITO_USERPOOL_ID: ${{ secrets.COGNITO_USERPOOL_ID }}
      run: |
        ./deploy.sh -e ${GITHUB_REF##*/}