name: Deploy

on:
  push:
    branches: [ master, develop ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      name: test name
      env:
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      run: |
        ./deploy.sh -e dev