name: Deploy

on:
  push:
    branches: [ master, develop ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      run: |
        echo "something"
        echo "$SUPER_SECRET"